server:
  port: 8089
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rjzfrj/my-spring-cloud-config/
          search-paths: respo
          username: 
          password: 
  application:
    name: cloud-config-serivce-eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true